r_arm_cart_imped_controller:
  type: imped_control/ImpedControlPlugin
  root_name: base
  tip_name: r_gripper_r_finger_tip

l_arm_cart_imped_controller:
  type: imped_control/ImpedControlPlugin
  root_name: base
  tip_name: l_gripper_l_finger_tip
